/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComposeRouteImport } from './routes/compose'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as SentRouteImport } from './routes/sent'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as FaxIdRouteImport } from './routes/fax.$id'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as SendJobIdRouteImport } from './routes/send.$jobId'
import { Route as ApiLineSendRouteImport } from './routes/api/line.send'
import { Route as ApiLineStatusRouteImport } from './routes/api/line.status'
import { Route as ApiLineFaxSidRouteImport } from './routes/api/line.fax.$sid'
import { Route as ApiLineMediaTokenRouteImport } from './routes/api/line.media.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposeRoute = ComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const SentRoute = SentRouteImport.update({
  id: '/sent',
  path: '/sent',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const FaxIdRoute = FaxIdRouteImport.update({
  id: '/fax/$id',
  path: '/fax/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SendJobIdRoute = SendJobIdRouteImport.update({
  id: '/send/$jobId',
  path: '/send/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLineSendRoute = ApiLineSendRouteImport.update({
  id: '/api/line/send',
  path: '/api/line/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLineStatusRoute = ApiLineStatusRouteImport.update({
  id: '/api/line/status',
  path: '/api/line/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLineFaxSidRoute = ApiLineFaxSidRouteImport.update({
  id: '/api/line/fax/$sid',
  path: '/api/line/fax/$sid',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLineMediaTokenRoute = ApiLineMediaTokenRouteImport.update({
  id: '/api/line/media/$token',
  path: '/api/line/media/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compose': typeof ComposeRoute
  '/contacts': typeof ContactsRoute
  '/inbox': typeof InboxRoute
  '/sent': typeof SentRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/wallet': typeof WalletRoute
  '/fax/$id': typeof FaxIdRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/send/$jobId': typeof SendJobIdRoute
  '/api/line/send': typeof ApiLineSendRoute
  '/api/line/status': typeof ApiLineStatusRoute
  '/api/line/fax/$sid': typeof ApiLineFaxSidRoute
  '/api/line/media/$token': typeof ApiLineMediaTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compose': typeof ComposeRoute
  '/contacts': typeof ContactsRoute
  '/inbox': typeof InboxRoute
  '/sent': typeof SentRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/wallet': typeof WalletRoute
  '/fax/$id': typeof FaxIdRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/send/$jobId': typeof SendJobIdRoute
  '/api/line/send': typeof ApiLineSendRoute
  '/api/line/status': typeof ApiLineStatusRoute
  '/api/line/fax/$sid': typeof ApiLineFaxSidRoute
  '/api/line/media/$token': typeof ApiLineMediaTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compose': typeof ComposeRoute
  '/contacts': typeof ContactsRoute
  '/inbox': typeof InboxRoute
  '/sent': typeof SentRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/wallet': typeof WalletRoute
  '/fax/$id': typeof FaxIdRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/send/$jobId': typeof SendJobIdRoute
  '/api/line/send': typeof ApiLineSendRoute
  '/api/line/status': typeof ApiLineStatusRoute
  '/api/line/fax/$sid': typeof ApiLineFaxSidRoute
  '/api/line/media/$token': typeof ApiLineMediaTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compose'
    | '/contacts'
    | '/inbox'
    | '/sent'
    | '/settings'
    | '/shop'
    | '/wallet'
    | '/fax/$id'
    | '/legal/privacy'
    | '/legal/terms'
    | '/send/$jobId'
    | '/api/line/send'
    | '/api/line/status'
    | '/api/line/fax/$sid'
    | '/api/line/media/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compose'
    | '/contacts'
    | '/inbox'
    | '/sent'
    | '/settings'
    | '/shop'
    | '/wallet'
    | '/fax/$id'
    | '/legal/privacy'
    | '/legal/terms'
    | '/send/$jobId'
    | '/api/line/send'
    | '/api/line/status'
    | '/api/line/fax/$sid'
    | '/api/line/media/$token'
  id:
    | '__root__'
    | '/'
    | '/compose'
    | '/contacts'
    | '/inbox'
    | '/sent'
    | '/settings'
    | '/shop'
    | '/wallet'
    | '/fax/$id'
    | '/legal/privacy'
    | '/legal/terms'
    | '/send/$jobId'
    | '/api/line/send'
    | '/api/line/status'
    | '/api/line/fax/$sid'
    | '/api/line/media/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComposeRoute: typeof ComposeRoute
  ContactsRoute: typeof ContactsRoute
  InboxRoute: typeof InboxRoute
  SentRoute: typeof SentRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  WalletRoute: typeof WalletRoute
  FaxIdRoute: typeof FaxIdRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  SendJobIdRoute: typeof SendJobIdRoute
  ApiLineSendRoute: typeof ApiLineSendRoute
  ApiLineStatusRoute: typeof ApiLineStatusRoute
  ApiLineFaxSidRoute: typeof ApiLineFaxSidRoute
  ApiLineMediaTokenRoute: typeof ApiLineMediaTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compose': {
      id: '/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof ComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sent': {
      id: '/sent'
      path: '/sent'
      fullPath: '/sent'
      preLoaderRoute: typeof SentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fax/$id': {
      id: '/fax/$id'
      path: '/fax/$id'
      fullPath: '/fax/$id'
      preLoaderRoute: typeof FaxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send/$jobId': {
      id: '/send/$jobId'
      path: '/send/$jobId'
      fullPath: '/send/$jobId'
      preLoaderRoute: typeof SendJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/line/send': {
      id: '/api/line/send'
      path: '/api/line/send'
      fullPath: '/api/line/send'
      preLoaderRoute: typeof ApiLineSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/line/status': {
      id: '/api/line/status'
      path: '/api/line/status'
      fullPath: '/api/line/status'
      preLoaderRoute: typeof ApiLineStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/line/fax/$sid': {
      id: '/api/line/fax/$sid'
      path: '/api/line/fax/$sid'
      fullPath: '/api/line/fax/$sid'
      preLoaderRoute: typeof ApiLineFaxSidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/line/media/$token': {
      id: '/api/line/media/$token'
      path: '/api/line/media/$token'
      fullPath: '/api/line/media/$token'
      preLoaderRoute: typeof ApiLineMediaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComposeRoute: ComposeRoute,
  ContactsRoute: ContactsRoute,
  InboxRoute: InboxRoute,
  SentRoute: SentRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  WalletRoute: WalletRoute,
  FaxIdRoute: FaxIdRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  SendJobIdRoute: SendJobIdRoute,
  ApiLineSendRoute: ApiLineSendRoute,
  ApiLineStatusRoute: ApiLineStatusRoute,
  ApiLineFaxSidRoute: ApiLineFaxSidRoute,
  ApiLineMediaTokenRoute: ApiLineMediaTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
